version: '3'

tasks:
  dev:
    cmds:
     - wails dev
  build:
    cmds:
      - wails build -clean -tags exp_gowebview2loader

  assets:
    cmds:
      - esbuild --bundle --minify css/index.css > public/bundle.css

